
name: "Push Github Pages"
on:
  push:
    branches:
      - dev
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: organized_baboon

jobs:
  export-web:
    if: true
    name: Web Export ğŸŒ
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout â˜‘ï¸
        uses: actions/checkout@v1
      - name: Setup âš™ï¸
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web build ğŸ”¨
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" ./build/web/index.html
      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync ğŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.
